-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 11:05:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pillam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pillam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pillam` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pillam` ;

-- -----------------------------------------------------
-- Table `pillam`.`escalador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`escalador` (
  `id_escalador` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(100) NULL DEFAULT NULL,
  `edat` INT NULL DEFAULT NULL,
  `nivell_maxim` VARCHAR(5) NULL DEFAULT NULL,
  `estil_preferit` ENUM('esportiva', 'classica', 'gel') NULL DEFAULT NULL,
  `historial` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`escola` (
  `id_escola` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `lloc` VARCHAR(100) NULL DEFAULT NULL,
  `aproximacio` TEXT NULL DEFAULT NULL,
  `numero_vies` INT NULL DEFAULT '0',
  `popularitat` ENUM('baixa', 'mitjana', 'alta') NULL DEFAULT NULL,
  `restriccions` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_escola`),
  UNIQUE INDEX `nom` (`nom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`sector` (
  `id_sector` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `coordenades` VARCHAR(100) NULL DEFAULT NULL,
  `aproximacio` TEXT NULL DEFAULT NULL,
  `numero_vies` INT NULL DEFAULT '0',
  `popularitat` ENUM('baixa', 'mitjana', 'alta') NULL DEFAULT NULL,
  `restriccions` TEXT NULL DEFAULT NULL,
  `escola_id` INT NOT NULL,
  PRIMARY KEY (`id_sector`),
  UNIQUE INDEX `nom` (`nom` ASC, `escola_id` ASC) VISIBLE,
  INDEX `escola_id` (`escola_id` ASC) VISIBLE,
  CONSTRAINT `sector_ibfk_1`
    FOREIGN KEY (`escola_id`)
    REFERENCES `pillam`.`escola` (`id_escola`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`via`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`via` (
  `id_via` INT NOT NULL AUTO_INCREMENT,
  `sector_id` INT NULL DEFAULT NULL,
  `creador_id` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `tipus_via` ENUM('esportiva', 'classica', 'gel') NOT NULL,
  `orientacio` ENUM('N', 'NE', 'NO', 'SE', 'SO', 'E', 'O', 'S') NULL DEFAULT NULL,
  `estat` ENUM('apte', 'construccio', 'tancada') NULL DEFAULT 'apte',
  `data_fi_estat` DATE NULL DEFAULT NULL,
  `ancoratge` VARCHAR(20) NULL DEFAULT NULL,
  `tipus_roca` ENUM('conglomerat', 'granit', 'calcaria', 'arenisca', 'altres') NULL DEFAULT NULL,
  `grau` CHAR(4) NULL,
  `restriccions` TINYINT NULL,
  PRIMARY KEY (`id_via`),
  INDEX `sector_id` (`sector_id` ASC) VISIBLE,
  INDEX `fk_via_escalador1_idx` (`creador_id` ASC) VISIBLE,
  CONSTRAINT `via_ibfk_2`
    FOREIGN KEY (`sector_id`)
    REFERENCES `pillam`.`sector` (`id_sector`),
  CONSTRAINT `fk_via_escalador1`
    FOREIGN KEY (`creador_id`)
    REFERENCES `pillam`.`escalador` (`id_escalador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`llarg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`llarg` (
  `id_llarg` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `via_id` INT NULL DEFAULT NULL,
  `llargada_llarg` INT NULL DEFAULT NULL,
  `NºLlarg` INT NULL,
  `llargada_total` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`id_llarg`),
  UNIQUE INDEX `id_llarg` (`id_llarg` ASC) VISIBLE,
  INDEX `via_id` (`via_id` ASC) VISIBLE,
  CONSTRAINT `llarg_ibfk_1`
    FOREIGN KEY (`via_id`)
    REFERENCES `pillam`.`via` (`id_via`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`via_classica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`via_classica` (
  `id_via` INT NOT NULL,
  PRIMARY KEY (`id_via`),
  CONSTRAINT `via_classica_ibfk_1`
    FOREIGN KEY (`id_via`)
    REFERENCES `pillam`.`via` (`id_via`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`Vias_hechas_Escaladore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`Via_Check_Escalador` (
  `via_id` INT NOT NULL,
  `escalador_id` INT NOT NULL,
  PRIMARY KEY (`via_id`, `escalador_id`),
  INDEX `escalador_id` (`escalador_id` ASC) VISIBLE,
  CONSTRAINT `via_creador_ibfk_1`
    FOREIGN KEY (`via_id`)
    REFERENCES `pillam`.`via` (`id_via`),
  CONSTRAINT `via_creador_ibfk_2`
    FOREIGN KEY (`escalador_id`)
    REFERENCES `pillam`.`escalador` (`id_escalador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`via_esportiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`via_esportiva` (
  `id_via` INT NOT NULL,
  `llargada` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_via`),
  CONSTRAINT `via_esportiva_ibfk_1`
    FOREIGN KEY (`id_via`)
    REFERENCES `pillam`.`via` (`id_via`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pillam`.`via_gel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pillam`.`via_gel` (
  `id_via` INT NOT NULL,
  PRIMARY KEY (`id_via`),
  CONSTRAINT `via_gel_ibfk_1`
    FOREIGN KEY (`id_via`)
    REFERENCES `pillam`.`via` (`id_via`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
