#MYSQL
db.type=mysql
db.url=jdbc:mysql://127.0.0.1:3306/Pillam
db.user=root
db.pass=Blanes2007!

#Postgres
# db.type=postgres
# db.url=jdbc:postgresql://localhost:5432/Pillam
# db.user=postgres
# db.pass=xxxx