# MYSQL
db.mysql.url=jdbc:mysql://localhost:3306/pillam
db.mysql.user=root
db.mysql.pass=GM*UPr3s4sP@#
#db.mysql.pass=Blanes2007!

# POSTGRESQL
db.postgres.url=jdbc:postgresql://localhost:5432/pillam
db.postgres.user=root
db.postgres.pass=Blanes2007!